spring:
  freemarker:
    allow-request-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html;
    suffix: .ftl
    template-loader-path: classpath:/templates/
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true